services:
  - type: web
    name: smart-complaint-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: TOKEN_SECRET
        generateValue: true
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false

  - type: web
    name: smart-complaint-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_BASE_URL
        sync: false
